name: clever
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.2.3

  provider: ^6.0.1
  uuid: ^3.0.5
  flutter_multi_formatter: ^2.4.1

  pin_view: ^1.0.1

  cupertino_icons: ^1.0.2
  image_picker_web: ^2.0.3+1
  mime_type: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-VariableFont_wght.ttf
