name: clever
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.2.3

  provider: ^6.0.1
  uuid: ^3.0.5
  flutter_multi_formatter: ^2.4.1

  pin_view: ^1.0.1

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  file_picker: ^4.3.0
  flutter_dropzone: ^3.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/img/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-VariableFont_wght.ttf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
